name: CHROMATIC

on:
  push:
    branches: ['master', 'dev']
    
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        
      - name: Install Dependencies
        run: yarn
        working-directory: storybook-static
        
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          working-directory: storybook-static
