name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [16.x]

    env:
      CI: ''
      REACT_APP_SERVICE_URL: ${{secrets.REACT_APP_SERVICE_URL}}
      REACT_APP_KAKAO_CLIENT_ID: ${{secrets.REACT_APP_KAKAO_CLIENT_ID}}

    steps:
      - name: Checkout source code
        uses: actions/checkout@main

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://${{ secrets.DEV_AWS_S3_BUCKET }}/dist --delete
          aws s3 cp index.html s3://${{ secrets.DEV_AWS_S3_BUCKET }}/

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.DEV_AWS_DISTRIBUTION_ID}} --paths "/*"
