name: STAGING-AWS-DEPLOY

on:
  push:
    branches:
      - dev

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Environment Variables File for Production
        run: |
          echo "REACT_APP_KAKAO_CLIENT_ID=$DEV_REACT_APP_KAKAO_CLIENT_ID" >> .env.staging
          echo "REACT_APP_SERVICE_URL=$DEV_REACT_APP_SERVICE_URL" >> .env.staging
          echo "REACT_APP_SERVER_URL=$DEV_REACT_APP_SERVER_URL" >> .env.staging
        env:
          REACT_APP_KAKAO_CLIENT_ID: ${{ secrets.DEV_REACT_APP_KAKAO_CLIENT_ID }}
          REACT_APP_SERVICE_URL: ${{ secrets.DEV_REACT_APP_SERVICE_URL }}
          REACT_APP_SERVER_URL: ${{ secrets.DEV_REACT_APP_SERVER_URL }}

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn run build:staging

      - name: Upload S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.DEV_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          SOURCE_DIR: 'dist'
          DEST_DIR: 'dist'

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          PATHS: '/*'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          DISTRIBUTION: ${{ secrets.DEV_AWS_DISTRIBUTION_ID }}
